name: mati_rest_api
description: A wrapper for the Metamap REST API.
version: 2.0.0
homepage: https://github.com/tomassasovsky/mati_rest_api.dart

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  equatable: ^2.0.5
  http: ^1.2.0
  http_interceptor:
    git:
      url: https://github.com/CodingAleCR/http_interceptor
      ref: main
  jwt_decoder: ^2.0.1
  meta: ^1.9.1
  recase: ^4.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.2
  very_good_analysis: ^4.0.0+1
