name: mati_rest_api
description: A wrapper for the Metamap REST API.
version: 1.0.0+1-beta
homepage: https://github.com/tomassasovsky/mati_rest_api.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  http_interceptor: ^2.0.0-beta.6
  jwt_decoder: ^2.0.1
  meta: ^1.8.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.6
  very_good_analysis: ^3.1.0
