name: mati_rest_api
description: A wrapper for the Metamap REST API.
version: 1.0.1+1-beta
homepage: https://github.com/tomassasovsky/mati_rest_api.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.17.1
  equatable: ^2.0.5
  http: ^0.13.5
  http_interceptor: ^1.0.2
  jwt_decoder: ^2.0.1
  meta: ^1.9.1
  recase: ^4.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.6
  very_good_analysis: ^4.0.0+1
